# Generated by Django 5.0.4 on 2024-05-24 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Service', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='input_concepts',
        ),
        migrations.RemoveField(
            model_name='service',
            name='output_concepts',
        ),
        migrations.DeleteModel(
            name='Concept',
        ),
        migrations.DeleteModel(
            name='Service',
        ),
    ]
