# Generated by Django 5.0.4 on 2024-05-24 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Service', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='cost',
        ),
    ]
