# Generated by Django 5.0.4 on 2024-05-24 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Service', '0004_remove_service_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='cost',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
